### ISSUE TITLE
flacpicture only works for v1 of go-flac

### ISSUE THREAD

**Issue by taurusxin** [go-flac/flacpicture#2]
flacpicture now requires go-flac@v1, but I need to use go-flac v2

**Comment by eternal-flame-AD** [comment]
I think I already is? Are you using /v2 for both packages?

https://github.com/go-flac/flacpicture/blob/31ea0aa5c085bb4da3c17455e1c3c7ed15c4ac12/v2/go.mod#L5

Rel: https://github.com/go-flac/go-flac/issues/5#issuecomment-2264580388

**Comment by taurusxin** [comment]
I was wrong, the go.mod in the v2 folder under the master branch still depends on v1

**Comment by eternal-flame-AD** [comment]
Oh thanks for pointing that out, I will update the head tomorrow
